### ISSUE TITLE
部署alarm时候失败

### ISSUE THREAD

**Issue by jx10086** [leancloud/satori#19]
---> Running in 94a6e9d2c594
Creating directory '/alarm/eggs'.
Creating directory '/alarm/bin'.
Creating directory '/alarm/parts'.
Creating directory '/alarm/develop-eggs'.
Develop: '/alarm/.'
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Got zc.recipe.egg 2.0.3.
Getting distribution for 'pbp.recipe.noserunner'.
Got pbp.recipe.noserunner 0.2.6.
Getting distribution for 'nose'.
no previously-included directories found matching 'doc/.build'
Got nose 1.3.7.
Getting distribution for 'plone.recipe.command'.
Got plone.recipe.command 1.1.
Installing app.
Getting distribution for 'ipython'.
error: Setup script exited with error in ipython setup command: Invalid environment marker: sys_platform == "win32" and python_version < "3.6"
An error occurred when trying to install /tmp/tmpDqu6PPget_dist/ipython-5.3.0.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing app.
  Getting distribution for 'ipython'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zc.buildout-2.9.2-py2.7.egg/zc/buildout/buildout.py", line 1982, in main
    getattr(buildout, command)(args)
  File "/usr/local/lib/python2.7/dist-packages/zc.buildout-2.9.2-py2.7.egg/zc/buildout/buildout.py", line 668, in install
    installed_files = self[part]._call(recipe.install)
  File "/usr/local/lib/python2.7/dist-packages/zc.buildout-2.9.2-py2.7.egg/zc/buildout/buildout.py", line 1419, in _call
    return f()
  File "/alarm/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/alarm/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/usr/local/lib/python2.7/dist-packages/zc.buildout-2.9.2-py2.7.egg/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/usr/local/lib/python2.7/dist-packages/zc.buildout-2.9.2-py2.7.egg/zc/buildout/easy_install.py", line 665, in install
    for dist in self._get_dist(requirement, ws):
  File "/usr/local/lib/python2.7/dist-packages/zc.buildout-2.9.2-py2.7.egg/zc/buildout/easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/usr/local/lib/python2.7/dist-packages/zc.buildout-2.9.2-py2.7.egg/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack
ERROR: Service 'alarm' failed to build: The command '/bin/sh -c cd /alarm && buildout' returned a non-zero code: 1

**Comment by feisuzhu** [comment]
Fixed in master
